Repository desmos-labs/desmos-bindings, pull requests merged in 2022-09, with the labels that each got.

#56 build(ci): decrease ci execution time
  .github/workflows/chain_interaction.yml
  .github/workflows/desmos_bindings.yml
  .github/workflows/publish_bindings.yml
Labels: kind/ci, automerge

#57 docs: fix doc errors
  packages/bindings/src/reactions/mocks.rs
  packages/bindings/src/reactions/models.rs
  packages/bindings/src/reactions/msg.rs
Labels: documentation, automerge

#59 build(ci): add action to ensure PR title matches Conventional Commits
  .github/workflows/lint-pr.yml
Labels: automerge

#38 feat: improve mock desmos app
  .changeset/entries/650788f8dcfa621b3335dea24ec32013613e575162cd6544b5928feae4d7a261.yaml
  Cargo.lock
  packages/bindings/src/mocks/mock_apps.rs
  packages/bindings/src/mocks/mock_keeper.rs
  packages/bindings/src/mocks/mod.rs
Labels: automerge

#58 feat!: add utility to mock query responses when performing unit tests
  .changeset/entries/f70d5114f858b93fc2301c78ad5e8ed2519efbacb39d1994670ad71830ffa2c8.yaml
  packages/bindings/src/mocks/mock_queriers.rs
  packages/bindings/src/posts/querier.rs
  packages/bindings/src/profiles/querier.rs
  packages/bindings/src/reactions/querier.rs
  packages/bindings/src/relationships/querier.rs
  packages/bindings/src/reports/querier.rs
  packages/bindings/src/subspaces/querier.rs
Labels: automerge

#63 chore: update desmos-bindings docs generation config
  packages/bindings/Cargo.toml
Labels: automerge

#64 ci: reduced test chain block time to reduce ci execution time
  .github/workflows/chain_interaction.yml
  desmos/spawn_test_chain.sh
Labels: kind/ci, automerge
